/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.CDC;

import business.Business;
import business.Organization.CDCOrganization;
import business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author mac
 */
public class CDCWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    CDCOrganization cdcOrganization;
    Business business;

    public CDCWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CDCOrganization cdcOrganization, Business business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.cdcOrganization = cdcOrganization;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVaccineReport = new javax.swing.JButton();
        btnVaccineRequest = new javax.swing.JButton();
        btnInventoryTracking = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1024, 768));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CDC Workarea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1020, 50));

        btnVaccineReport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVaccineReport.setText("Vaccine Event Summary");
        btnVaccineReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaccineReportActionPerformed(evt);
            }
        });
        add(btnVaccineReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 315, 39));

        btnVaccineRequest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVaccineRequest.setText("Vaccine Request Management");
        btnVaccineRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaccineRequestActionPerformed(evt);
            }
        });
        add(btnVaccineRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 315, 41));

        btnInventoryTracking.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInventoryTracking.setText("Inventory Tracking");
        btnInventoryTracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryTrackingActionPerformed(evt);
            }
        });
        add(btnInventoryTracking, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 315, 39));
    }// </editor-fold>//GEN-END:initComponents

    private void btnVaccineReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaccineReportActionPerformed
        // TODO add your handling code here:
        CDCEventMgtJPanel cdcEventMgtJPanel = new CDCEventMgtJPanel(userProcessContainer, account, cdcOrganization, business);
        userProcessContainer.add("CDCEventMgtJPanel", cdcEventMgtJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnVaccineReportActionPerformed

    private void btnVaccineRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaccineRequestActionPerformed
        // TODO add your handling code here:
        VaccineRequestManagementJPanel vaccineRequestManagementJPanel = new VaccineRequestManagementJPanel(userProcessContainer, account, cdcOrganization, business);
        userProcessContainer.add("VaccineRequestManagementJPanel", vaccineRequestManagementJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnVaccineRequestActionPerformed

    private void btnInventoryTrackingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryTrackingActionPerformed
        // TODO add your handling code here:
        CDCInventoryTrackingJPanel cdcInventoryTrackingJPanel = new CDCInventoryTrackingJPanel(userProcessContainer, account, cdcOrganization, business);
        userProcessContainer.add("CDCInventoryTrackingJPanel", cdcInventoryTrackingJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnInventoryTrackingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventoryTracking;
    private javax.swing.JButton btnVaccineReport;
    private javax.swing.JButton btnVaccineRequest;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
